### ISSUE TITLE
QQ登录之后获取不到loginInfo

### ISSUE THREAD

**Issue by DukeCheng** [tinysnake/microsoft-owin-security-qq#3]
用下列配置的时候：
`            //app.UseQQConnectAuthentication(new Microsoft.Owin.Security.QQ.QQConnectAuthenticationOptions()
            //{
            //    AppId = "101294257",
            //    AppSecret = "10ef6f7c0f935d892c058f240474645d",
            //    //Caption = "QQ登录"
            //    //SignInAsAuthenticationType = "QQ登录",
            //});`
在回调处理方法中，通过
`        [AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Login");
            }`
无法获取到loginInfo, 这里获取到的loginInfo=null,

但是通过下面的配置是正确的:
`            app.UseQQConnectAuthentication(appId: "appid", appSecret: "secret");`

**Comment by tinysnake** [comment]
因为工作没有继续接触ASP.NET Web相关, 所以此项目已经很多年没有更新了,很早就落伍了.

另外你暴露了你的appId和secret,我已经把它们干掉了.
